// <auto-generated />
using DotNET_Console_Application.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNET_Console_Application.Migrations
{
    [DbContext(typeof(CarsContext))]
    [Migration("20250404011840_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("DotNET_Console_Application.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("ID");

                    b.ToTable("manufacturer");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            ID = -2,
                            Name = "Honda"
                        },
                        new
                        {
                            ID = -3,
                            Name = "Toyota"
                        },
                        new
                        {
                            ID = -4,
                            Name = "Nissan"
                        });
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Model", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ManufacturerID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("ID");

                    b.HasIndex("ManufacturerID")
                        .HasDatabaseName("FK_Model_Manufacturer");

                    b.ToTable("model");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            ManufacturerID = -1,
                            Name = "Eclipse"
                        },
                        new
                        {
                            ID = -2,
                            ManufacturerID = -1,
                            Name = "3000GT"
                        },
                        new
                        {
                            ID = -3,
                            ManufacturerID = -2,
                            Name = "NSX"
                        },
                        new
                        {
                            ID = -4,
                            ManufacturerID = -2,
                            Name = "S2000"
                        },
                        new
                        {
                            ID = -5,
                            ManufacturerID = -3,
                            Name = "Supra"
                        },
                        new
                        {
                            ID = -6,
                            ManufacturerID = -3,
                            Name = "MR2"
                        },
                        new
                        {
                            ID = -7,
                            ManufacturerID = -4,
                            Name = "300ZX"
                        },
                        new
                        {
                            ID = -8,
                            ManufacturerID = -4,
                            Name = "GTR"
                        });
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Vehicle", b =>
                {
                    b.Property<string>("VIN")
                        .HasColumnType("TEXT")
                        .HasColumnName("vin");

                    b.Property<int>("ModelID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<int>("Odometer")
                        .HasColumnType("INTEGER")
                        .HasColumnName("odometer");

                    b.HasKey("VIN");

                    b.HasIndex("ModelID")
                        .HasDatabaseName("FK_Vehicle_Model");

                    b.ToTable("vehicle");

                    b.HasData(
                        new
                        {
                            VIN = "4A3AL54F3XE067712",
                            ModelID = -1,
                            Odometer = 100
                        },
                        new
                        {
                            VIN = "JA3AN74K8XY001384",
                            ModelID = -2,
                            Odometer = 100
                        },
                        new
                        {
                            VIN = "JH4NA1153MT000743",
                            ModelID = -3,
                            Odometer = 100
                        },
                        new
                        {
                            VIN = "JHMAP21475S008443",
                            ModelID = -4,
                            Odometer = 100
                        },
                        new
                        {
                            VIN = "JT2JA82J8S0028274",
                            ModelID = -5,
                            Odometer = 100
                        },
                        new
                        {
                            VIN = "JTDFR320320052403",
                            ModelID = -6,
                            Odometer = 100
                        },
                        new
                        {
                            VIN = "JN1RZ24A1LX002317",
                            ModelID = -7,
                            Odometer = 100
                        },
                        new
                        {
                            VIN = "-----BCNR33004655",
                            ModelID = -8,
                            Odometer = 100
                        });
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Model", b =>
                {
                    b.HasOne("DotNET_Console_Application.Models.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_Model_Manufacturer");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Vehicle", b =>
                {
                    b.HasOne("DotNET_Console_Application.Models.Model", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_Vehicle_Model");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Manufacturer", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Model", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
