// <auto-generated />
using DotNET_Console_Application.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNET_Console_Application.Migrations
{
    [DbContext(typeof(CodeFirstContext))]
    [Migration("20250404012345_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("DotNET_Console_Application.Models.ClassRoom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("room_number");

                    b.HasKey("ID");

                    b.ToTable("course");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            RoomNumber = "101A"
                        },
                        new
                        {
                            ID = -2,
                            RoomNumber = "101B"
                        });
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("ClassID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("course_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.HasKey("ID");

                    b.HasIndex("ClassID")
                        .HasDatabaseName("FK_Student_ClassRoom");

                    b.ToTable("student");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            ClassID = -1,
                            FirstName = "Jane",
                            LastName = "Doe"
                        });
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Student", b =>
                {
                    b.HasOne("DotNET_Console_Application.Models.ClassRoom", "ClassRoom")
                        .WithMany("Students")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Student_ClassRoom");

                    b.Navigation("ClassRoom");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.ClassRoom", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
