// <auto-generated />
using DotNET_Console_Application.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNET_Console_Application.Migrations
{
    [DbContext(typeof(CarsContext))]
    [Migration("20250404010925_Odometer")]
    partial class Odometer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("DotNET_Console_Application.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("manufacturer");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("model");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Vehicle", b =>
                {
                    b.Property<string>("Vin")
                        .HasColumnType("TEXT")
                        .HasColumnName("vin");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<int>("odometer")
                        .HasColumnType("INTEGER")
                        .HasColumnName("odometer");

                    b.HasKey("Vin");

                    b.HasIndex("ModelId");

                    b.ToTable("vehicle");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Model", b =>
                {
                    b.HasOne("DotNET_Console_Application.Models.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerId")
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Vehicle", b =>
                {
                    b.HasOne("DotNET_Console_Application.Models.Model", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelId")
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Manufacturer", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Model", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
